[package]
authors = ["Isaac Muzzey <isaac.muzzey@mines.sdsmt.edu>"]
edition = "2021"
name = "regexer"
description = "A simple Rust regex parser"
version = "0.1.0"
rust-version = "1.83"


[dependencies]
color-eyre = "0.6.3"
crossterm = "0.28.1"
ratatui = "0.29.0"
tui-textarea = "0.7.0"
